/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MachineIdRouteImport } from './routes/$machineId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MachineIdIndexRouteImport } from './routes/$machineId/index'
import { Route as ApiV1LeaderboardRouteImport } from './routes/api/v1/leaderboard'
import { Route as ApiV1ImageRouteImport } from './routes/api/v1/image'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1EventsRouteImport } from './routes/api/v1/events'
import { Route as ApiV1StatsWeekdayRouteImport } from './routes/api/v1/stats/weekday'
import { Route as ApiV1StatsProjectDailyRouteImport } from './routes/api/v1/stats/project-daily'
import { Route as ApiV1StatsLanguagesRouteImport } from './routes/api/v1/stats/languages'
import { Route as ApiV1StatsDailyTotalsRouteImport } from './routes/api/v1/stats/daily-totals'

const MachineIdRoute = MachineIdRouteImport.update({
  id: '/$machineId',
  path: '/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineIdIndexRoute = MachineIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MachineIdRoute,
} as any)
const ApiV1LeaderboardRoute = ApiV1LeaderboardRouteImport.update({
  id: '/api/v1/leaderboard',
  path: '/api/v1/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ImageRoute = ApiV1ImageRouteImport.update({
  id: '/api/v1/image',
  path: '/api/v1/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventsRoute = ApiV1EventsRouteImport.update({
  id: '/api/v1/events',
  path: '/api/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StatsWeekdayRoute = ApiV1StatsWeekdayRouteImport.update({
  id: '/api/v1/stats/weekday',
  path: '/api/v1/stats/weekday',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StatsProjectDailyRoute = ApiV1StatsProjectDailyRouteImport.update({
  id: '/api/v1/stats/project-daily',
  path: '/api/v1/stats/project-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StatsLanguagesRoute = ApiV1StatsLanguagesRouteImport.update({
  id: '/api/v1/stats/languages',
  path: '/api/v1/stats/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StatsDailyTotalsRoute = ApiV1StatsDailyTotalsRouteImport.update({
  id: '/api/v1/stats/daily-totals',
  path: '/api/v1/stats/daily-totals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$machineId': typeof MachineIdRouteWithChildren
  '/$machineId/': typeof MachineIdIndexRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/image': typeof ApiV1ImageRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/api/v1/stats/daily-totals': typeof ApiV1StatsDailyTotalsRoute
  '/api/v1/stats/languages': typeof ApiV1StatsLanguagesRoute
  '/api/v1/stats/project-daily': typeof ApiV1StatsProjectDailyRoute
  '/api/v1/stats/weekday': typeof ApiV1StatsWeekdayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$machineId': typeof MachineIdIndexRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/image': typeof ApiV1ImageRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/api/v1/stats/daily-totals': typeof ApiV1StatsDailyTotalsRoute
  '/api/v1/stats/languages': typeof ApiV1StatsLanguagesRoute
  '/api/v1/stats/project-daily': typeof ApiV1StatsProjectDailyRoute
  '/api/v1/stats/weekday': typeof ApiV1StatsWeekdayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$machineId': typeof MachineIdRouteWithChildren
  '/$machineId/': typeof MachineIdIndexRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/image': typeof ApiV1ImageRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/api/v1/stats/daily-totals': typeof ApiV1StatsDailyTotalsRoute
  '/api/v1/stats/languages': typeof ApiV1StatsLanguagesRoute
  '/api/v1/stats/project-daily': typeof ApiV1StatsProjectDailyRoute
  '/api/v1/stats/weekday': typeof ApiV1StatsWeekdayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$machineId'
    | '/$machineId/'
    | '/api/v1/events'
    | '/api/v1/health'
    | '/api/v1/image'
    | '/api/v1/leaderboard'
    | '/api/v1/stats/daily-totals'
    | '/api/v1/stats/languages'
    | '/api/v1/stats/project-daily'
    | '/api/v1/stats/weekday'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$machineId'
    | '/api/v1/events'
    | '/api/v1/health'
    | '/api/v1/image'
    | '/api/v1/leaderboard'
    | '/api/v1/stats/daily-totals'
    | '/api/v1/stats/languages'
    | '/api/v1/stats/project-daily'
    | '/api/v1/stats/weekday'
  id:
    | '__root__'
    | '/'
    | '/$machineId'
    | '/$machineId/'
    | '/api/v1/events'
    | '/api/v1/health'
    | '/api/v1/image'
    | '/api/v1/leaderboard'
    | '/api/v1/stats/daily-totals'
    | '/api/v1/stats/languages'
    | '/api/v1/stats/project-daily'
    | '/api/v1/stats/weekday'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MachineIdRoute: typeof MachineIdRouteWithChildren
  ApiV1EventsRoute: typeof ApiV1EventsRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1ImageRoute: typeof ApiV1ImageRoute
  ApiV1LeaderboardRoute: typeof ApiV1LeaderboardRoute
  ApiV1StatsDailyTotalsRoute: typeof ApiV1StatsDailyTotalsRoute
  ApiV1StatsLanguagesRoute: typeof ApiV1StatsLanguagesRoute
  ApiV1StatsProjectDailyRoute: typeof ApiV1StatsProjectDailyRoute
  ApiV1StatsWeekdayRoute: typeof ApiV1StatsWeekdayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$machineId': {
      id: '/$machineId'
      path: '/$machineId'
      fullPath: '/$machineId'
      preLoaderRoute: typeof MachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$machineId/': {
      id: '/$machineId/'
      path: '/'
      fullPath: '/$machineId/'
      preLoaderRoute: typeof MachineIdIndexRouteImport
      parentRoute: typeof MachineIdRoute
    }
    '/api/v1/leaderboard': {
      id: '/api/v1/leaderboard'
      path: '/api/v1/leaderboard'
      fullPath: '/api/v1/leaderboard'
      preLoaderRoute: typeof ApiV1LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/image': {
      id: '/api/v1/image'
      path: '/api/v1/image'
      fullPath: '/api/v1/image'
      preLoaderRoute: typeof ApiV1ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/events': {
      id: '/api/v1/events'
      path: '/api/v1/events'
      fullPath: '/api/v1/events'
      preLoaderRoute: typeof ApiV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/stats/weekday': {
      id: '/api/v1/stats/weekday'
      path: '/api/v1/stats/weekday'
      fullPath: '/api/v1/stats/weekday'
      preLoaderRoute: typeof ApiV1StatsWeekdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/stats/project-daily': {
      id: '/api/v1/stats/project-daily'
      path: '/api/v1/stats/project-daily'
      fullPath: '/api/v1/stats/project-daily'
      preLoaderRoute: typeof ApiV1StatsProjectDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/stats/languages': {
      id: '/api/v1/stats/languages'
      path: '/api/v1/stats/languages'
      fullPath: '/api/v1/stats/languages'
      preLoaderRoute: typeof ApiV1StatsLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/stats/daily-totals': {
      id: '/api/v1/stats/daily-totals'
      path: '/api/v1/stats/daily-totals'
      fullPath: '/api/v1/stats/daily-totals'
      preLoaderRoute: typeof ApiV1StatsDailyTotalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MachineIdRouteChildren {
  MachineIdIndexRoute: typeof MachineIdIndexRoute
}

const MachineIdRouteChildren: MachineIdRouteChildren = {
  MachineIdIndexRoute: MachineIdIndexRoute,
}

const MachineIdRouteWithChildren = MachineIdRoute._addFileChildren(
  MachineIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MachineIdRoute: MachineIdRouteWithChildren,
  ApiV1EventsRoute: ApiV1EventsRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1ImageRoute: ApiV1ImageRoute,
  ApiV1LeaderboardRoute: ApiV1LeaderboardRoute,
  ApiV1StatsDailyTotalsRoute: ApiV1StatsDailyTotalsRoute,
  ApiV1StatsLanguagesRoute: ApiV1StatsLanguagesRoute,
  ApiV1StatsProjectDailyRoute: ApiV1StatsProjectDailyRoute,
  ApiV1StatsWeekdayRoute: ApiV1StatsWeekdayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
